services:
  postgres:
    image: postgres:16-alpine
    container_name: archivio-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ArchivioLessicaleDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d ArchivioLessicaleDb"]
      interval: 3s
      timeout: 3s
      retries: 5

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: archivio-api-container
    restart: on-failure
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "5000:8080"
    environment:
      - ConnectionStrings__DefaultConnection=Host=postgres;Port=5432;Database=ArchivioLessicaleDb;Username=postgres;Password=postgres
      - ASPNETCORE_ENVIRONMENT=Development

  pgadmin:
    image: dpage/pgadmin4
    container_name: archivio-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin        # <--- ДОБАВИЛИ ЭТУ СТРОКУ
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  pgadmin_data:                              # <--- И ОБЪЯВИЛИ ТОМ ЗДЕСЬ
